# Generated by Django 4.0.1 on 2022-02-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'ongoing'), ('3', 'finished'), ('4', 'delete')], default='1', max_length=1),
        ),
    ]
